import { Recorder, MAX_RECORDING_BYTES } from './recorder.js';
const config = await fetch('/config.json').then((r) => r.json()).catch(() => ({ mode: 'local', apiUrl: '/api' }));
const $ = (id) => document.getElementById(id); let selectedFile; let selectedId; let recording = false;
const recorder = new Recorder((blob, extension) => { selectedFile = new File([blob], `recording-${Date.now()}.${extension}`, { type: blob.type }); $('submit').disabled = false; $('record').textContent = '● 다시 녹음'; recording = false; notice(`${formatBytes(blob.size)} 녹음 준비 완료`); }, (seconds) => $('timer').textContent = `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`);

$('record').onclick = async () => { try { if (recording) { recorder.stop(); $('record').textContent='처리 중...'; } else { await recorder.start(); recording=true; $('record').textContent='■ 녹음 종료'; notice('녹음 중'); } } catch (e) { notice(e.message, true); } };
$('file').onchange = () => { selectedFile = $('file').files[0]; $('submit').disabled = !selectedFile; if(selectedFile) notice(`${selectedFile.name} 선택됨`); };
$('recordTab').onclick=()=>tab(true); $('fileTab').onclick=()=>tab(false); $('refresh').onclick=loadMeetings; $('login').onclick=login;
$('submit').onclick = async () => { if (!selectedFile || selectedFile.size > MAX_RECORDING_BYTES) return notice('500MB 이하 오디오 파일을 선택하세요.', true); try { $('submit').disabled=true; notice('업로드 URL 생성 중...'); const created=await api('/meetings',{method:'POST',body:JSON.stringify({fileName:selectedFile.name,contentType:normalizeType(selectedFile),fileSize:selectedFile.size,languageCode:$('language').value,speakerCount:Number($('speakers').value)})}); const form=new FormData(); Object.entries(created.upload.fields).forEach(([key,value])=>form.append(key,value)); form.append('file',selectedFile); const upload=await fetch(created.upload.url,{method:'POST',body:form}); if(!upload.ok) throw new Error('업로드에 실패했습니다.'); await api(`/meetings/${created.meetingId}/start`,{method:'POST'}); notice('처리를 시작했습니다. 완료되면 목록에 표시됩니다.'); await loadMeetings(); } catch(e){notice(e.message,true)} finally{$('submit').disabled=false} };

async function loadMeetings(){ try{const data=await api('/meetings'); $('meetings').innerHTML=data.meetings.length?data.meetings.map((m)=>`<button class="meeting ${m.meetingId===selectedId?'selected':''}" data-id="${m.meetingId}"><span class="status">${escapeHtml(m.status)}</span><strong>${escapeHtml(m.analysis?.title||m.fileName)}</strong><small>${new Date(m.createdAt).toLocaleString()}</small></button>`).join(''):'<p>아직 회의가 없습니다.</p>'; document.querySelectorAll('.meeting').forEach((el)=>el.onclick=()=>showMeeting(el.dataset.id)); }catch(e){notice(e.message,true)} }
async function showMeeting(id){selectedId=id; const m=await api(`/meetings/${id}`); if(m.status!=='READY'){ $('detail').innerHTML=`<div class="empty"><span class="status">${m.status}</span><h2>${escapeHtml(m.fileName)}</h2><p>전사와 분석을 처리하고 있습니다.</p></div>`; return loadMeetings(); } const a=m.analysis; $('detail').innerHTML=`<span class="status">READY</span><h1>${escapeHtml(a.title)}</h1><p>${escapeHtml(a.summary)}</p><div class="grid"><section class="panel"><h2>결정사항</h2>${a.decisions.map(d=>`<p><strong>${escapeHtml(d.text)}</strong><br><small>근거: ${escapeHtml(d.evidence)}</small></p>`).join('')||'<p>명시된 결정사항이 없습니다.</p>'}</section><section class="panel"><h2>액션아이템</h2><div class="actions">${a.actionItems.map(x=>`<label class="action ${x.status==='DONE'?'done':''}"><input type="checkbox" data-action="${x.id}" ${x.status==='DONE'?'checked':''}><span>${escapeHtml(x.task)}<br><small>${escapeHtml(x.owner||'담당자 미정')}</small></span></label>`).join('')||'<p>명시된 후속 작업이 없습니다.</p>'}</div></section></div><section class="panel"><h2>열린 질문</h2>${a.openQuestions.map(q=>`<p>${escapeHtml(q)}</p>`).join('')||'<p>없음</p>'}</section><details class="panel"><summary>전체 전사 보기</summary><pre>${escapeHtml(m.transcript)}</pre></details>`; document.querySelectorAll('[data-action]').forEach(el=>el.onchange=async()=>{await api(`/meetings/${id}/actions/${el.dataset.action}`,{method:'PATCH',body:JSON.stringify({status:el.checked?'DONE':'OPEN'})});showMeeting(id)}); loadMeetings(); }
async function api(path,options={}){const headers={'content-type':'application/json'};if(config.mode==='aws'){const token=JSON.parse(localStorage.getItem('meeting_memory_tokens')||'{}').id_token;if(!token){login();throw new Error('로그인이 필요합니다.')}headers.authorization=`Bearer ${token}`}const result=await fetch(`${config.apiUrl}${path}`,{...options,headers});const body=await result.json();if(!result.ok)throw new Error(body.error||'요청에 실패했습니다.');return body}
async function login(){if(config.mode!=='aws')return notice('로컬 모드에서는 인증을 생략합니다.');const bytes=crypto.getRandomValues(new Uint8Array(32));const verifier=btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');sessionStorage.setItem('pkce_verifier',verifier);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(digest))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');location.href=`${config.authDomain}/oauth2/authorize?${new URLSearchParams({response_type:'code',client_id:config.clientId,redirect_uri:config.redirectUri,scope:'openid email',code_challenge_method:'S256',code_challenge:challenge})}`}
function tab(record){$('recordPanel').hidden=!record;$('filePanel').hidden=record;$('recordTab').classList.toggle('active',record);$('fileTab').classList.toggle('active',!record)}function notice(text,error=false){$('notice').textContent=text;$('notice').style.color=error?'#b42318':'#256f5b'}function formatBytes(n){return `${(n/1024/1024).toFixed(1)}MB`}function normalizeType(file){if(file.type==='audio/x-m4a')return 'audio/x-m4a';if(file.type==='audio/mp4')return 'audio/mp4';if(file.type==='audio/mpeg')return 'audio/mpeg';if(file.type==='audio/wav'||file.type==='audio/x-wav')return 'audio/wav';return 'audio/webm'}function escapeHtml(v=''){const d=document.createElement('div');d.textContent=String(v);return d.innerHTML}loadMeetings();setInterval(()=>{if(selectedId)showMeeting(selectedId);else loadMeetings()},10000);
